modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="ravageandcabbage" #mandatory
version="0.1.2" #mandatory
displayName="Ravage & Cabbage" #mandatory
credits="Coda (Assets, Code, and Ideas), Ninni (Assets), Larry (Building and Ideas), & superlord9362 (Code)" #optional
authors="superlord9362" #optional
description='''A fun mod adding cabbages and expanding ravagers!'''
[[dependencies.ravageandcabbage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
